USE ist1110887;

-- Create the MEASUREMENTS table
DROP TABLE MEASUREMENTS;
CREATE TABLE IF NOT EXISTS MEASUREMENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MEASURE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALUE DECIMAL(10,2) NOT NULL,
    SENSORID TEXT NOT NULL
);

-- Create the FOOTAGE table
CREATE TABLE IF NOT EXISTS FOOTAGE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FOOTAGE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FILENAME VARCHAR(256) NOT NULL,
    STATUS BOOLEAN NOT NULL
);
