USE ist1110887;

-- Create the MEASUREMENTS table
DROP TABLE MEASUREMENTS;
CREATE TABLE IF NOT EXISTS MEASUREMENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MEASURE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALUE DECIMAL(10,2) NOT NULL,
    SENSORID TEXT NOT NULL
);

-- Create the FOOTAGE table
CREATE TABLE IF NOT EXISTS FOOTAGE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FOOTAGE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MEDIA_DATA LONGBLOB NOT NULL, -- Use LONGBLOB for binary data
    INSERTED_CODE TEXT NOT NULL
);

-- Example to handle the LONGBLOB column

-- Insert into FOOTAGE with base64 encoded string
INSERT INTO FOOTAGE (CURRENT_TIMESTAMP, MEDIA_DATA, INSERTED_CODE)
VALUES ('2024-03-05 12:00:00', FROM_BASE64('your_base64_encoded_string'), 'your_inserted_code');

-- Select current timestamp and encode MEDIA_DATA to base64
SELECT CURRENT_TIMESTAMP, TO_BASE64(MEDIA_DATA) AS MEDIA_DATA_BASE64
FROM FOOTAGE;
